//
// Created by 陶诚程 on 2021/1/24.
//

#ifndef CPP_DEFINE_H
#define CPP_DEFINE_H


struct TreeNode {
    int val;
    TreeNode *left;
    TreeNode *right;
    TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
};

struct ListNode {
    int val;
    ListNode *next;
    ListNode(int x) : val(x), next(nullptr) {}
};

#include "array/239. Sliding Window Maximum.hpp"
#include "array/396. Rotate Function.hpp"
#include "array/417. Pacific Atlantic Water Flow.hpp"
#include "array/1470. Shuffle the Array.hpp"
#include "array/1471. The k Strongest Values in an Array.hpp"
#include "array/1465. Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts.hpp"
#include "array/1481. Least Number of Unique Integers after K Removals.hpp"
#include "array/1477. Find Two Non-overlapping Sub-arrays Each With Target Sum.hpp"
#include "array/435. Non-overlapping Intervals.hpp"
#include "array/436. Find Right Interval.hpp"
#include "array/1493. Longest Subarray of 1's After Deleting One Element.hpp"
#include "array/1497. Check If Array Pairs Are Divisible by k.hpp"
#include "array/456. 132 Pattern.hpp"
#include "array/498. Diagonal Traverse.hpp"
#include "array/525. Contiguous Array.hpp"
#include "array/846. Hand of Straights.hpp"
#include "array/983. Minimum Cost For Tickets.hpp"
#include "array/532. K-diff Pairs in an Array.hpp"
#include "array/598. Range Addition II.hpp"
#include "array/661. Image Smoother.hpp"
#include "array/932. Beautiful Array.hpp"
#include "array/735. Asteroid Collision.hpp"
#include "array/1536. Minimum Swaps to Arrange a Binary Grid.hpp"
#include "array/870. Advantage Shuffle.hpp"
#include "array/954. Array of Doubled Pairs.hpp"
#include "array/1024. Video Stitching.hpp"
#include "array/1049. Last Stone Weight II.hpp"
#include "array/1054. Distant Barcodes.hpp"
#include "array/1187. Make Array Strictly Increasing.hpp"
#include "array/1488. Avoid Flood in The City.hpp"
#include "array/1509. Minimum Difference Between Largest and Smallest Value in Three Moves.hpp"
#include "array/1626. Best Team With No Conflicts.hpp"
#include "array/1673. Find the Most Competitive Subsequence.hpp"
#include "array/1562. Find Latest Group of Size M.hpp"
#include "array/315. Count of Smaller Numbers After Self.hpp"
#include "array/1365. How Many Numbers Are Smaller Than the Current Number.hpp"
#include "array/324. Wiggle Sort II.hpp"
#include "array/84. Largest Rectangle in Histogram.hpp"
#include "array/1738. Find Kth Largest XOR Coordinate Value.hpp"
#include "array/1508. Range Sum of Sorted Subarray Sums.hpp"
#include "array/322. Coin Change.hpp"
#include "array/1743. Restore the Array From Adjacent Pairs.hpp"
#include "array/1546. Maximum Number of Non-Overlapping Subarrays With Sum Equals Target.hpp"
#include "array/1705. Maximum Number of Eaten Apples.hpp"
#include "array/37. Sudoku Solver.hpp"
#include "array/4. Median of Two Sorted Arrays.hpp"
#include "array/688. Knight Probability in Chessboard.hpp"
#include "array/1769. Minimum Number of Operations to Move All Balls to Each Box.hpp"
#include "array/1770. Maximum Score from Performing Multiplication Operations.hpp"
#include "array/1775. Equal Sum Arrays With Minimum Number of Operations.hpp"
#include "array/350. Intersection of Two Arrays II.hpp"
#include "array/406. Queue Reconstruction by Height.hpp"
#include "array/407. Trapping Rain Water II.hpp"
#include "array/410. Split Array Largest Sum.hpp"
#include "array/1806. Minimum Number of Operations to Reinitialize a Permutation.hpp"
#include "array/1812. Determine Color of a Chessboard Square.hpp"
#include "array/1817. Finding the Users Active Minutes.hpp"
#include "array/1818. Minimum Absolute Sum Difference.hpp"
#include "array/480. Sliding Window Median.hpp"
#include "array/493. Reverse Pairs.hpp"
#include "array/862. Shortest Subarray with Sum at Least K.hpp"
#include "array/1887. Reduction Operations to Make the Array Elements Equal.hpp"
#include "array/975. Odd Even Jump.hpp"
#include "array/1909. Remove One Element to Make the Array Strictly Increasing.hpp"
#include "array/1964. Find the Longest Valid Obstacle Course at Each Position.hpp"
#include "array/1943. Describe the Painting.hpp"
#include "array/1439. Find the Kth Smallest Sum of a Matrix With Sorted Rows.hpp"
#include "number/229. Majority Element II.hpp"
#include "number/220. Contains Duplicate III.hpp"
#include "number/1441. Build an Array With Stack Operations.hpp"
#include "number/1442. Count Triplets That Can Form Two Arrays of Equal XOR.hpp"
#include "number/1447. Simplified Fractions.hpp"
#include "number/368. Largest Divisible Subset.hpp"
#include "number/343. Integer Break.hpp"
#include "number/373. Find K Pairs with Smallest Sums.hpp"
#include "number/376. Wiggle Subsequence.hpp"
#include "number/386. Lexicographical Numbers.hpp"
#include "number/390. Elimination Game.hpp"
#include "number/397. Integer Replacement.hpp"
#include "number/1464. Maximum Product of Two Elements in an Array.hpp"
#include "number/1475. Final Prices With a Special Discount in a Shop.hpp"
#include "number/1492. The kth Factor of n.hpp"
#include "number/1498. Number of Subsequences That Satisfy the Given Sum Condition.hpp"
#include "number/464. Can I Win.hpp"
#include "number/492. Construct the Rectangle.hpp"
#include "number/507. Perfect Number.hpp"
#include "number/703. Kth Largest Element in a Stream.hpp"
#include "number/682. Baseball Game.hpp"
#include "number/717. 1-bit and 2-bit Characters.hpp"
#include "number/762. Prime Number of Set Bits in Binary Representation.hpp"
#include "number/788. Rotated Digits.hpp"
#include "number/812. Largest Triangle Area.hpp"
#include "number/1518. Water Bottles.hpp"
#include "number/868. Binary Gap.hpp"
#include "number/219. Contains Duplicate II.hpp"
#include "number/31. Next Permutation.hpp"
#include "number/166. Fraction to Recurring Decimal.hpp"
#include "number/241. Different Ways to Add Parentheses.hpp"
#include "number/659. Split Array into Consecutive Subsequences.hpp"
#include "number/781. Rabbits in Forest.hpp"
#include "number/1619. Mean of Array After Removing Some Elements.hpp"
#include "number/853. Car Fleet.hpp"
#include "number/295. Find Median from Data Stream.hpp"
#include "number/1647. Minimum Deletions to Make Character Frequencies Unique.hpp"
#include "number/612. Shortest Distance in a Plane.hpp"
#include "number/1734. Decode XORed Permutation.hpp"
#include "number/1736. Latest Time by Replacing Hidden Digits.hpp"
#include "number/477. Total Hamming Distance.hpp"
#include "number/60. Permutation Sequence.hpp"
#include "number/357. Count Numbers with Unique Digits.hpp"
#include "number/486. Predict the Winner.hpp"
#include "number/1742. Maximum Number of Balls in a Box.hpp"
#include "number/1760. Minimum Limit of Balls in a Bag.hpp"
#include "number/1774. Closest Dessert Cost.hpp"
#include "number/1792. Maximum Average Pass Ratio.hpp"
#include "number/347. Top K Frequent Elements.hpp"
#include "number/363. Max Sum of Rectangle No Larger Than K.hpp"
#include "number/414. Third Maximum Number.hpp"
#include "number/378. Kth Smallest Element in a Sorted Matrix.hpp"
#include "number/1823. Find the Winner of the Circular Game.hpp"
#include "number/518. Coin Change 2.hpp"
#include "number/575. Distribute Candies.hpp"
#include "number/1834. Single-Threaded CPU.hpp"
#include "number/1838. Frequency of the Most Frequent Element.hpp"
#include "number/629. K Inverse Pairs Array.hpp"
#include "number/632. Smallest Range Covering Elements from K Lists.hpp"
#include "number/1850. Minimum Adjacent Swaps to Reach the Kth Smallest Number.hpp"
#include "number/667. Beautiful Arrangement II.hpp"
#include "number/672. Bulb Switcher II.hpp"
#include "number/1854. Maximum Population Year.hpp"
#include "number/786. K-th Smallest Prime Fraction.hpp"
#include "number/857. Minimum Cost to Hire K Workers.hpp"
#include "number/1005. Maximize Sum Of Array After K Negations.hpp"
#include "number/1235. Maximum Profit in Job Scheduling.hpp"
#include "number/1353. Maximum Number of Events That Can Be Attended.hpp"
#include "number/1942. The Number of the Smallest Unoccupied Chair.hpp"
#include "number/1354. Construct Target Array With Multiple Sums.hpp"
#include "number/1357. Apply Discount Every n Orders.hpp"
#include "number/1383. Maximum Performance of a Team.hpp"
#include "number/1396. Design Underground System.hpp"
#include "tree/1443. Minimum Time to Collect All Apples in a Tree.cpp"
#include "tree/1457. Pseudo-Palindromic Paths in a Binary Tree.hpp"
#include "tree/450. Delete Node in a BST.hpp"
#include "tree/449. Serialize and Deserialize BST.hpp"
#include "tree/987. Vertical Order Traversal of a Binary Tree.hpp"
#include "tree/988. Smallest String Starting From Leaf.hpp"
#include "tree/297. Serialize and Deserialize Binary Tree.hpp"
#include "graph/207. Course Schedule.hpp"
#include "graph/210. Course Schedule II.hpp"
#include "graph/1444. Number of Ways of Cutting a Pizza.hpp"
#include "graph/310. Minimum Height Trees.hpp"
#include "graph/355. Design Twitter.hpp"
#include "graph/1466. Reorder Routes to Make All Paths Lead to the City Zero.hpp"
#include "graph/399. Evaluate Division.hpp"
#include "graph/433. Minimum Genetic Mutation.hpp"
#include "graph/1472. Design Browser History.hpp"
#include "graph/1476. Subrectangle Queries.hpp"
#include "graph/1496. Path Crossing.hpp"
#include "graph/452. Minimum Number of Arrows to Burst Balloons.hpp"
#include "graph/5536. Maximal Network Rank.hpp"
#include "graph/874. Walking Robot Simulation.hpp"
#include "graph/883. Projection Area of 3D Shapes.hpp"
#include "graph/892. Surface Area of 3D Shapes.hpp"
#include "graph/547. Friend Circles.hpp"
#include "graph/677. Map Sum Pairs.hpp"
#include "graph/721. Accounts Merge.hpp"
#include "graph/911. Online Election.hpp"
#include "graph/981. Time Based Key-Value Store.hpp"
#include "graph/1146. Snapshot Array.hpp"
#include "graph/1584. Min Cost to Connect All Points.hpp"
#include "graph/1727. Largest Submatrix With Rearrangements.hpp"
#include "graph/51. N-Queens.hpp"
#include "graph/52. N-Queens II.hpp"
#include "graph/1366. Rank Teams by Votes.hpp"
#include "graph/743. Network Delay Time.hpp"
#include "graph/787. Cheapest Flights Within K Stops.hpp"
#include "graph/684. Redundant Connection.hpp"
#include "graph/332. Reconstruct Itinerary.hpp"
#include "graph/502. IPO.hpp"
#include "graph/514. Freedom Trail.hpp"
#include "graph/1824. Minimum Sideway Jumps.hpp"
#include "graph/497. Random Point in Non-overlapping Rectangles.hpp"
#include "graph/630. Course Schedule III.hpp"
#include "graph/675. Cut Off Trees for Golf Event.hpp"
#include "graph/699. Falling Squares.hpp"
#include "graph/1882. Process Tasks Using Servers.hpp"
#include "graph/778. Swim in Rising Water.hpp"
#include "graph/826. Most Profit Assigning Work.hpp"
#include "graph/851. Loud and Rich.hpp"
#include "graph/847. Shortest Path Visiting All Nodes.hpp"
#include "graph/871. Minimum Number of Refueling Stops.hpp"
#include "graph/882. Reachable Nodes In Subdivided Graph.hpp"
#include "graph/1326. Minimum Number of Taps to Open to Water a Garden.hpp"
#include "graph/1348. Tweet Counts Per Frequency.hpp"
#include "graph/1368. Minimum Cost to Make at Least One Valid Path in a Grid.hpp"
#include "string/1446. Consecutive Characters.cpp"
#include "string/1451. Rearrange Words in a Sentence.hpp"
#include "string/1455. Check If a Word Occurs As a Prefix of Any Word in a Sentence.hpp"
#include "string/1456. Maximum Number of Vowels in a Substring of Given Length.hpp"
#include "string/424. Longest Repeating Character Replacement.hpp"
#include "string/474. Ones and Zeroes.hpp"
#include "string/482. License Key Formatting.hpp"
#include "string/1507. Reformat Date.hpp"
#include "string/744. Find Smallest Letter Greater Than Target.hpp"
#include "string/748. Shortest Completing Word.hpp"
#include "string/806. Number of Lines To Write String.hpp"
#include "string/824. Goat Latin.hpp"
#include "string/893. Groups of Special-Equivalent Strings.hpp"
#include "string/937. Reorder Data in Log Files.hpp"
#include "string/692. Top K Frequent Words.hpp"
#include "string/5535. Maximum Nesting Depth of the Parentheses.hpp"
#include "string/1616. Split Two Strings to Make Palindrome.hpp"
#include "string/955. Delete Columns to Make Sorted II.hpp"
#include "string/1209. Remove All Adjacent Duplicates in String II.hpp"
#include "string/942. DI String Match.hpp"
#include "string/1079. Letter Tile Possibilities.hpp"
#include "string/535. Encode and Decode TinyURL.hpp"
#include "string/1419. Minimum Number of Frogs Croaking.hpp"
#include "string/567. Permutation in String.hpp"
#include "string/44. Wildcard Matching.hpp"
#include "string/3. Longest Substring Without Repeating Characters.hpp"
#include "string/316. Remove Duplicate Letters.hpp"
#include "string/97. Interleaving String.hpp"
#include "string/752. Open the Lock.hpp"
#include "string/1768. Merge Strings Alternately.hpp"
#include "string/242. Valid Anagram.hpp"
#include "string/516. Longest Palindromic Subsequence.hpp"
#include "string/1839. Longest Substring Of All Vowels in Order.hpp"
#include "string/726. Number of Atoms.hpp"
#include "string/745. Prefix and Suffix Search.hpp"
#include "string/767. Reorganize String.hpp"
#include "string/833. Find And Replace in String.hpp"
#include "string/854. K-Similar Strings.hpp"
#include "string/1239. Maximum Length of a Concatenated String with Unique Characters.hpp"
#include "string/2002. Maximum Product of the Length of Two Palindromic Subsequences.hpp"
#include "list/1483. Kth Ancestor of a Tree Node.hpp"
#include "list/445. Add Two Numbers II.hpp"
#include "list/138. Copy List with Random Pointer.hpp"
#include "list/25. Reverse Nodes in k-Group.hpp"
#include "list/729. My Calendar I.hpp"
#include "list/731. My Calendar II.hpp"
#include "list/146. LRU Cache.hpp"
#include "list/206. Reverse Linked List.hpp"
#include "list/352. Data Stream as Disjoint Intervals.hpp"
#include "list/460. LFU Cache.hpp"
#include "list/432. All O`one Data Structure.hpp"
#include "list/503. Next Greater Element II.hpp"
#include "list/649. Dota2 Senate.hpp"
#include "list/705. Design HashSet.hpp"
#include "list/706. Design HashMap.hpp"
#include "list/707. Design Linked List.hpp"
#include "list/710. Random Pick with Blacklist.hpp"
#include "list/715. Range Module.hpp"
#include "list/855. Exam Room.hpp"
#include "list/895. Maximum Frequency Stack.hpp"
#include "list/973. K Closest Points to Origin.hpp"
#include "list/1172. Dinner Plate Stacks.hpp"
#include "list/1206. Design Skiplist.hpp"
#include "thread/1115. Print FooBar Alternately.hpp"
#include "thread/1116. Print Zero Even Odd.hpp"

#endif //CPP_DEFINE_H
